apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
  namespace: default
spec:
  terminationGracePeriodSeconds: 3
  containers:
    - name: kubectl-container
      image: bitnami/kubectl:latest
      command:
        - "sleep"
        - "infinity"